### ISSUE TITLE
为了显示表情需，代码里面需要做哪些设置呢？

### ISSUE THREAD

**Issue by alanchen1988** [guange2015/OHAttributedLabel#1]
我在显示表情的时候遇到一个问题，能解析出表情的 字符串，但是不能显示，代码里面需要做什么设置吗？

希望得到您的回复，谢谢

**Comment by guange2015** [comment]
查看这个文件里面emoite的定义 OHAttributedLabel / OHAttributedLabel / TagParsers / OHASBasicHTMLParser.m 

然后嵌入的代码为 [表情名]， 比如 `[睡觉]`

**Comment by alanchen1988** [comment]
那个我有改过，然后我直接运行你的代码：
[foundString setEmoit:[NSString stringWithFormat:@"5-22-2.png|%@|%@",
                                           imgAttr[@"width"], imgAttr[@"height"]]];
我直接把所有的表情显示同一张图片了，在你的demo上面也没有显示，不明觉厉了。

**Comment by alanchen1988** [comment]
这个问题有解决方法吗？求赐教，非常感谢

**Comment by guange2015** [comment]
demo就可以直接跑通啊，里面都是现成的例子。

![](https://raw.github.com/hhuai/OHAttributedLabel/master/screenshot.png)

**Comment by jy03344894** [comment]
这个表情好像不能够连续出现

**Comment by alanchen1988** [comment]
你的sdk是多少的呢？
